### ISSUE TITLE
Newest version not on Pypi

### ISSUE THREAD

**Issue by beruic** [jazzband/sorl-thumbnail#515]
Newest version of Pypi is 12.4a1, not the newest release 12.4

**Comment by Flimm** [comment]
@camilonova committed a new commit bumping the version number, and committed the Git tag `v12.4`. Any member of Jazzband can commit new commits, however, we can't yet release anything on PyPI since we're still waiting on Jazzband roadies to set this up. Unfortunately, since he pushed a new Git tag, this is difficult to reverse.

Here are the relevant issues that we're waiting on until we can release the next version on PyPI:

- https://github.com/jazzband/sorl-thumbnail/issues/507
- https://github.com/jazzband/roadies/issues/69

Please go upvote them.
