### ISSUE TITLE
Please upload 12.6 release to PyPi (Django3 support)

### ISSUE THREAD

**Issue by devova** [jazzband/sorl-thumbnail#607]
Latest uploaded version still 12.5

**Comment by camilonova** [comment]
https://github.com/jazzband-roadies/help/issues/182

**Comment by bpepple** [comment]
> [jazzband-roadies/help#182](https://github.com/jazzband-roadies/help/issues/182)

So... is there any movement on this? I see they closed the reference issue, but still haven't uploaded the latest release to PyPi.

**Comment by benjaoming** [comment]
@bpepple I find the instructions a bit unclear after these commits. #610 says to fix the issue (and probably require a new tag and release) but also changes a lot of other things.

Unless someone says so, I think it should be released as a 0.13 version, especially since it removes Python 3.4 and 3.5 support - and please correct me if I'm wrong: https://github.com/jazzband/sorl-thumbnail/pull/610/files#r370096811

**Comment by danjac** [comment]
@beaugunderson currently sorl-thumbnail has been blocking projects from upgrading to Django 3.0 for a month already, so if these changes have been approved and merged it would be good to move ahead as soon as possible. If you want to bump up the versioning I'm sure that's fine, but the bigger issue is the long delay in getting a stable release out.

**Comment by zulrang** [comment]
What's the status of this?  The last update to PyPI was back in 2018!

**Comment by benjaoming** [comment]
@zulrang please give people the time they need and avoid unnecessary Github notification stress. A new release of sorl-thumbnail was tagged yesterday and can be approved for a PyPi release shortly.

**Comment by camilonova** [comment]
I'm on it. Will be done soon.

**Comment by camilonova** [comment]
Done

**Comment by hiaselhans** [comment]
:heart:
thank you! i am at django-3 now...
