### ISSUE TITLE
Django 4.1 template tag 'thumbnail' conflict with easy-thumbnails

### ISSUE THREAD

**Issue by MarcoGlauser** [jazzband/sorl-thumbnail#713]
Django 4.1 added a system check to find duplicate template tags at startup. If easy-thumbnails and sorl-thumbnails are installed in the same project, it will detect the possible clash and will exit with an error. This happens even if the tags are not used in any template.
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (templates.E003) 'thumbnail' is used for multiple template tag modules: 'easy_thumbnails.templatetags.thumbnail', 'sorl.thumbnail.templatetags.thumbnail'
```

I've added a minimal reproduction here:
https://github.com/MarcoGlauser/template_tag_conflict
Simply run a manage.py command like `makemigrations`

Related:
https://github.com/SmileyChris/easy-thumbnails/issues/609

**Comment by claudep** [comment]
Thanks to https://github.com/django/django/commit/f71b0cf769d9ac5, Django 4.1.2 will turn the error into a warning (which can be silenced). I'm not sure if we should do anything else here.

**Comment by alexsilva** [comment]
> Thanks to [django/django@f71b0cf769d9ac5](https://github.com/django/django/commit/f71b0cf769d9ac5), Django 4.1.2 will turn the error into a warning (which can be silenced). I'm not sure if we should do anything else here.

`'easy_thumbnails.templatetags.thumbnail', 'sorl.thumbnail.templatetags.thumbnail'`

This warning is because two apps have registered a tag with the same name 'thumbnail'. The side effect of this is that one tag will overlap another and a solution to this is to rename the tag.

sorl.thumbnail.templatetags.sorthumbnail

or

easy_thumbnails.templatetags.easythumbnail
