### ISSUE TITLE
Make THUMBNAIL_STORAGE contain a storage key

### ISSUE THREAD

**Issue by claudep** [jazzband/sorl-thumbnail#729]
THUMBNAIL_STORAGE should simply be a key of the `django.core.files.storage.storages` object. Then `sorl` would not need to fiddle with storage classes but could simply trust the Django storages machinery.

Of course, backwards compatibility should be guaranteed for some time.

**Comment by LarsAC** [comment]
May I ask what is the status of this ? Just setting the key to THUMBNAIL_STORAGES does not (as it expects module.class as a syntax).

I am using django-storages for an Azure storage account and cannot get sorl to work with it. But I am uncertain whether it actually should since the status of this issue is unclear to me ?

Lars

**Comment by claudep** [comment]
@LarsAC I made a tentative patch for this issue, maybe you could test it on your setup and tell me if it helps regarding your issue?

**Comment by paul673** [comment]
I am working on a django project which I would like to upgrade to version to 5.1. I am using django-wiki in the project which depends on sorl-thumbnail. The release notes for django-wiki state that it supports django 5.1. But it only works if i have the DEFAULT_FILE_STORAGE in my setting file. DEFAULT_FILE_STORAGE has been deprecated since 4.2 and has been removed in django 5.1. This change will probably solve this issue so i was wondering when a fixed version, with your changes, will be realeased? I appreciate your help.

**Comment by samuelm2** [comment]
I am also hitting this issue! Would love to know if anyone knows a workaround for the time being, or when we'll get a new version that has these fixes

**Comment by claudep** [comment]
People testing the master branch encountered some issues related to serialization. Please read the latest comments of #748. PR #780 is supposed to fix that. I would love to see other people testing that PR in real projects to confirm it's the right fix. It's the latest blocker issue to make a new release.

**Comment by llamafilm** [comment]
I found my way here because thumbnails are broken in Netbox. https://github.com/netbox-community/netbox/issues/20212

I tested your PR #780 and it works for me.
